package rules;
import com.example.WoTRecommender.model.Tank;
import com.example.WoTRecommender.model.User;
import com.example.WoTRecommender.model.Characteristics;

rule "Recommend tank based on characteristics chosen by user"
    salience ($characteristics.size()/$value)
    when
        $t: Tank($name: name, $characteristics: characteristics)
        $u: User($user_characteristics: user_characteristics) // user characteristics pick
        Number($value: intValue >= 1) from accumulate(
        	Characteristics($c:this, this memberOf $characteristics) from $user_characteristics,
        	count($c)
        )
    then
    	System.out.println("Tank that might be good for you: " + $name);
    	System.out.println("Number of tank characteristics that match your choice: " + $value + "/" + $characteristics.size());
    	System.out.println("Final tank:" + $t);
    	modify($u) { setCurrentTank($t) }
end

